export const IPC_CHANNELS = {
  systemGetCliHealth: "system:getCliHealth",
  systemPickProjectDirectory: "system:pickProjectDirectory",
  systemOpenProjectPath: "system:openProjectPath",
  projectsList: "projects:list",
  projectsCreate: "projects:create",
  projectsRemove: "projects:remove",
  projectsSelect: "projects:select",
  threadsList: "threads:list",
  threadsCreate: "threads:create",
  threadsRename: "threads:rename",
  threadsDelete: "threads:delete",
  threadsOpen: "threads:open",
  threadsUpdateModel: "threads:updateModel",
  threadsUpdateReasoning: "threads:updateReasoning",
  chatSend: "chat:send",
  chatStop: "chat:stop",
  chatRetry: "chat:retry",
  chatResolvePermission: "chat:resolvePermission",
  chatGetModels: "chat:getModels",
  chatRefreshModels: "chat:refreshModels",
  chatEvent: "chat:event",
  gitGetStatus: "git:getStatus",
  gitListChangedFiles: "git:listChangedFiles",
  gitCommitAndPush: "git:commitAndPush",
  settingsGet: "settings:get",
  settingsUpdate: "settings:update"
} as const;
